import './miniatures.js';
import './big-pic.js';
import './upload-photo.js';
import './image-scale.js';
import './image-effects.js';
import './form-validation.js';
import './create-fetch.js';
import './upload-form.js';
import './filter.js';
